/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testPackage;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Aadesh Randeria
 */
public class Tabbed extends javax.swing.JPanel {

    /**
     * Creates new form Tabbed
     */
    private JPanel container;
    public Tabbed(JPanel container) {
        initComponents();
        this.container = container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        barPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        piePanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        barPanel.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Bar Chart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        barPanel.add(jButton1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.addTab("My first Tab", barPanel);

        jPanel2.setLayout(new java.awt.BorderLayout());

        piePanel.setLayout(new java.awt.BorderLayout());

        jButton2.setText("Pie Chart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        piePanel.add(jButton2, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(piePanel, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("My second tab", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset barChartData = new DefaultCategoryDataset();
        barChartData.setValue(20000, "Contribution Amount", "Jan");
        barChartData.setValue(15000, "Contribution Amount", "Feb");
        barChartData.setValue(30000, "Contribution Amount", "Mar");
        JFreeChart barChart = ChartFactory.createBarChart("Church Contributions", "Monthly", "Contribution Amount", barChartData, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot barchrt = barChart.getCategoryPlot();
        barchrt.setRangeGridlinePaint(Color.ORANGE);
        ChartPanel barP = new ChartPanel(barChart);
        barP.setVisible(true);
        barPanel.removeAll();
        barPanel.add(barP, BorderLayout.CENTER);
        barPanel.validate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultPieDataset pieData = new DefaultPieDataset();
        pieData.setValue("One", new Integer(10));
        pieData.setValue("Two", new Integer(20));
        pieData.setValue("Three", new Integer(30));
        pieData.setValue("Four", new Integer(40));
        JFreeChart chart = ChartFactory.createPieChart("Pie Chart", pieData, true, true, true);
        PiePlot p = (PiePlot)chart.getPlot();
        ChartPanel chartpanel = new ChartPanel(chart);
        chartpanel.setVisible(true);
        piePanel.removeAll();
        piePanel.add(chartpanel, BorderLayout.CENTER);
        piePanel.validate();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel piePanel;
    // End of variables declaration//GEN-END:variables
}
