/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.Donor.Donor;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.MainCenterEnterprise;
import Business.Network.Network;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Role.DonorRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.Validations;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Apurva Sawant
 */
public class SignupJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignupJPanel
     */
    private JPanel jpanel;
    private EcoSystem system;
    public SignupJPanel(JPanel container, EcoSystem system) {
        initComponents();
        jpanel=container;
        this.system=system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        phoneNoTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        userNameTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        passvordTxt = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Enter your details:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 11, -1, -1));

        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 34, -1, -1));

        jLabel3.setText("Phone number:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 65, -1, -1));

        jLabel4.setText("Email id:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 96, -1, -1));

        jLabel5.setText("UserName:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 127, -1, -1));

        jLabel6.setText("Password:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 158, -1, -1));

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 31, 117, -1));

        phoneNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoTxtActionPerformed(evt);
            }
        });
        add(phoneNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 62, 117, -1));

        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 93, 117, -1));

        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 124, 117, -1));

        jLabel7.setText("Type:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 184, -1, -1));

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Individual", "Hotel", "Event" }));
        add(typeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 181, 117, -1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 219, -1, -1));
        add(passvordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 155, 117, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel8.setText("(example@eg.com)");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 70, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel9.setText("(xxx-xxx-xxxx)");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 70, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void phoneNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoTxtActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
          boolean nameFlag=false;
          boolean phoneNoFlag=false;
          boolean emailIdFlag=false; 
          boolean userFlag=false;
          boolean passFlag=false;
          Organization organization=null;
          for(Network network:system.getNetworkList())
          {
             for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList())
             {
                if(enterprise instanceof MainCenterEnterprise)
                {
                    for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList())
                    {
                       if(org instanceof DonorOrganization)   
                       {
                          organization=org;
                       }    
                    }    
                }    
             }    
          }    
          if(nameTxt.getText().isEmpty() )
          {
            nameFlag=true;
            JOptionPane.showMessageDialog(null, "Please enter your full name");
          }
          
          if(phoneNoTxt.getText().isEmpty() || !Validations.isPhoneNumber(phoneNoTxt.getText()))
          {
            phoneNoFlag=true;
            JOptionPane.showMessageDialog(null, "Please enter a valid phone number");
          }
          
          if(emailTxt.getText().isEmpty() || !Validations.isValidEmailId(emailTxt.getText()))
          {
            emailIdFlag=true;
            JOptionPane.showMessageDialog(null, "Please enter a valid EmailID");
          }
           if(userNameTxt.getText().isEmpty())
          {
            userFlag=true;
            JOptionPane.showMessageDialog(null, "Please enter your user name");
          }

          if(passvordTxt.getText().isEmpty() )
          {
            passFlag=true;
            JOptionPane.showMessageDialog(null, "Please enter a password");
          }
          
           if (!nameFlag & !phoneNoFlag & !emailIdFlag & !userFlag & !passFlag){
             
              UserAccount user=new UserAccount();
              user.setEmployee(null);
              Donor donor=new Donor();
              donor.setName(nameTxt.getText());
              donor.setEmailId(emailTxt.getText());
              donor.setPhoneNo(phoneNoTxt.getText());
              donor.setType(String.valueOf(typeComboBox.getSelectedItem()));
              user.setDonor(donor);
             // Role role=Role.RoleType.Donor;
              user.setRole(new DonorRole());
              user.setUsername(userNameTxt.getText());
              user.setPassword(String.valueOf(passvordTxt.getPassword()));
             // UserAccountDirectory userAccountDirectory=new UserAccountDirectory();
              organization.getUserAccountDirectory().addAccount(user);
             // userAccountDirectory.addAccount(user);
              JOptionPane.showMessageDialog(null, "Details saved successfully. You may login now");
              nameTxt.setText("");
              emailTxt.setText("");
              phoneNoTxt.setText("");
              userNameTxt.setText("");
              passvordTxt.setText("");
           }
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passvordTxt;
    private javax.swing.JTextField phoneNoTxt;
    private javax.swing.JButton submitButton;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
